### ISSUE TITLE
GameManager のマルチプレイ対応

### ISSUE THREAD

**Issue by dsuz** [PS18a-4thTerm/multiplay-fps#3]
現状では GameManager オブジェクトに追加されているコンポーネントはマルチプレイ対応しておらず、実行時にエラーが出る。

これをマルチプレイに対応させること。優先順位としては GameFlowManager と ObjectiveManger を最優先とする。

作業ブランチは gamemanagement でお願いします。

**Comment by laver9692** [comment]
とりあえずPlayerが全員死んだら負け。
敵をすべて倒したら勝利にします。

**Comment by dsuz** [comment]
一緒にプレイして、動作確認しました。
